"""
static_export.py -- generates a self-contained, uploadable clone of the
live mirror (port 5032) page.

Why this works without duplicating any rendering logic:
mirror.js does 100% of its rendering client-side, driven purely by
fetch() calls to a fixed, small set of JSON endpoints (see API_PATHS
below -- verified against every fetchJson() call in mirror.js). So
instead of re-implementing the widget rendering (clock, news ticker,
crypto, ...) in Python, this module:

  1. calls each of those endpoints once, in-process, via Flask's test
     client (no real HTTP hop, no extra process) -- reusing the exact
     same route handlers, caching and error handling as the live API,
     so the export can never drift from what the live mirror shows,
  2. bakes the resulting JSON into a small static-data.js,
  3. ships a tiny fetch-shim.js that intercepts mirror.js's fetch()
     calls and serves that baked JSON instead of hitting the (on an
     external host, unreachable) live API,
  4. copies mirror.js and mirror.css UNCHANGED.

Because mirror.js itself is never modified, every setInterval-driven
rotation/animation it already has (news ticker scroll, news source
rotation, compliments rotation, DEFCON rotation, the clock tick, ...)
keeps running exactly as on the live mirror -- just cycling over the
frozen snapshot instead of live data, which is invisible to a viewer
between one render and the next.

Call render_static_mirror() directly for a one-off export, or use
StaticMirrorScheduler to re-render on a timer (mirrors the design of
sftp_sync.SftpSyncService: settings are read fresh on every tick, so
changes made in the admin UI take effect without a restart).
"""
import base64
import json
import logging
import os
import re
import threading
import time
from datetime import datetime

log = logging.getLogger("static-export")

# Every path mirror.js's fetchJson() calls. Keep this in sync if mirror.js
# is ever extended with a new endpoint -- anything NOT in this list (and
# therefore not in static-data.js) falls back to a real fetch() at view
# time (see fetch-shim.js), which will simply fail on an external host
# with no network path back to the API -- better a visibly broken single
# widget than a silently stale/wrong one.
API_PATHS = [
    "/api/config",
    "/api/calendar",
    "/api/news",
    "/api/crypto",
    "/api/weather",
    "/api/stocks",
    "/api/quote",
    "/api/server-status",
    "/api/warnings",
    "/api/air-quality",
    "/api/elbe-pegel",
    "/api/ews",
    "/api/defcon",
    "/api/env-sensor",
]

DEFAULT_INTERVAL_MIN = 30
MIN_INTERVAL_MIN = 1
# Puffer nach dem eigentlichen Render-Intervall, bevor die Seite sich neu
# lädt -- damit der nächste SFTP-Upload sicher fertig ist, wenn der
# geöffnete Tab neu lädt, statt exakt mittendrin.
AUTO_RELOAD_BUFFER_MS = 30_000

# Config-Felder, die mirror.js clientseitig nie liest (nur server-seitig
# zum Abrufen der eigentlichen Daten gebraucht werden), aber die in
# /api/config unverändert mitgeliefert werden. Auf einem intern erreichbaren
# API-Port unkritisch -- landet die komplette Config aber (wie hier) in
# einer öffentlich hochgeladenen static-data.js, sind das echte Datenlecks
# (private Kalender-URL inkl. Secret-Token, API-Keys). Werden vor dem Export
# aus JEDEM Widget-Block entfernt, unabhängig vom Widget-Namen -- neue
# Secret-Felder müssen hier nur einmal ergänzt werden.
SENSITIVE_CONFIG_FIELDS = {"icalUrl", "apiKey", "password", "key", "token", "secret"}


def _scrub_config_snapshot(config_response):
    """Returns a deep copy of the /api/config JSON body with sensitive
    per-widget fields removed. Safe no-op if the shape isn't what's
    expected (e.g. an error response), so a scrub failure never blocks
    the export -- it just leaves that response as-is."""
    try:
        scrubbed = json.loads(json.dumps(config_response))  # cheap deep copy
        widgets = ((scrubbed.get("config") or {}).get("widgets") or {})
        for wcfg in widgets.values():
            if isinstance(wcfg, dict):
                for field in list(wcfg.keys()):
                    if field in SENSITIVE_CONFIG_FIELDS:
                        del wcfg[field]
        return scrubbed
    except Exception as e:
        log.error("Config scrub failed, exporting config unscrubbed: %s", e)
        return config_response

FETCH_SHIM_JS = """/* fetch-shim.js -- auto-generated by static_export.py, do not edit.
Intercepts mirror.js's fetch() calls and serves the pre-baked JSON in
MM_STATIC_DATA instead of hitting the live API (unreachable from an
externally hosted copy). Matches by checking whether the requested URL
CONTAINS a known API path, rather than parsing it with `new URL()` --
mirror.js builds that URL from location.hostname/protocol/port, which is
empty/nonsensical when the page is opened as a local file (file://) or
through some odd proxy setup, and `new URL()` throws on the result. A
plain substring check has no such edge case and works everywhere the
page itself loads, including a local double-click test before upload.
Anything not covered by the snapshot falls through to a real fetch(), so
an endpoint this exporter doesn't know about yet fails visibly instead
of silently. */
(() => {
    const realFetch = window.fetch.bind(window);
    const KNOWN_PATHS = Object.keys(window.MM_STATIC_DATA || {});
    window.fetch = (input, init) => {
        const url = typeof input === 'string' ? input : (input && input.url) || '';
        const path = KNOWN_PATHS.find((p) => url.indexOf(p) !== -1);
        if (path) {
            const data = window.MM_STATIC_DATA[path];
            return Promise.resolve(new Response(JSON.stringify(data), {
                status: 200,
                headers: { 'Content-Type': 'application/json' },
            }));
        }
        return realFetch(input, init);
    };
})();
"""

FONT_URL_RE = re.compile(r"url\('/assets/fonts/([^']+)'\)")
FONT_MIME = {".woff2": "font/woff2", ".woff": "font/woff", ".ttf": "font/ttf"}


def _inline_fonts_as_data_uris(css_text, fonts_dir):
    """Replaces every /assets/fonts/xxx.woff2 @font-face src with a base64
    data: URI, so the exported page needs zero extra font-file requests --
    it renders identically even if literally nothing but this one
    index.html ends up on the webserver. Fonts that can't be found are
    left as a (now-broken, since nothing serves /assets/fonts/... on an
    external host) relative reference -- the page still renders, just
    with the sans-serif fallback (see the fonts_dir note below)."""
    if not fonts_dir or not os.path.isdir(fonts_dir):
        return css_text, 0

    embedded = 0

    def _replace(match):
        nonlocal embedded
        fname = match.group(1)
        fpath = os.path.join(fonts_dir, fname)
        ext = os.path.splitext(fname)[1].lower()
        mime = FONT_MIME.get(ext)
        if not mime or not os.path.isfile(fpath):
            return match.group(0)
        with open(fpath, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        embedded += 1
        return f"url('data:{mime};base64,{b64}')"

    return FONT_URL_RE.sub(_replace, css_text), embedded


def _escape_for_inline_script(js_text):
    """A literal '</script' inside inlined JS would end the surrounding
    <script> tag early and break the page -- split the sequence apart so
    the browser's HTML parser never sees it as a real closing tag."""
    return js_text.replace("</script", "<\\/script")


def _fetch_snapshot(api_app):
    """Calls every endpoint in API_PATHS in-process via the Flask test
    client and returns {path: json_body}. Any single endpoint failing
    (e.g. a flaky RSS feed) doesn't abort the whole export -- it just
    gets an {"ok": False, ...} body, exactly like the live API would
    return, so the exported widget shows its normal "unavailable" state
    instead of blocking the render for every other widget."""
    snapshot = {}
    client = api_app.test_client()
    for path in API_PATHS:
        try:
            resp = client.get(path)
            body = resp.get_json()
            if path == "/api/config":
                body = _scrub_config_snapshot(body)
            snapshot[path] = body
        except Exception as e:
            log.error("Snapshot fetch failed for %s: %s", path, e)
            snapshot[path] = {"ok": False, "msg": str(e)}
    return snapshot


def _atomic_write(path, content):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)


def render_static_mirror(api_app, base_dir, publish_dir, fonts_dir=None, reload_interval_min=None):
    """Builds ONE self-contained index.html -- CSS, mirror.js, fetch-shim.js
    and the data snapshot all inlined, fonts embedded as base64 data URIs
    -- into publish_dir. Deliberately a single file (no mirror.css/
    mirror.js/static-data.js/assets/fonts/ siblings it depends on): that
    way there's no multi-file upload to get wrong, no missing-dependency
    failure mode, and the page renders correctly even if a webserver or
    SFTP sync only ever sees/serves that one file. Meant to be watched by
    sftp_sync.SftpSyncService (or any other directory-watching uploader).

    fonts_dir: where the @font-face .woff2 files actually live on disk.
    app.py's mirror_static route only serves static/mirror/*, but
    mirror.css references /assets/fonts/... (a path app.py itself
    doesn't serve) -- so on your server, tell me/set this explicitly to
    wherever those four inter-v13-latin-*.woff2 files are. If left
    unset, the export tries static/mirror/assets/fonts as a guess and,
    if that's empty too, the exported page simply falls back to the
    system sans-serif font (still very close visually to Inter) instead
    of failing.

    reload_interval_min: if set, a tiny script is embedded that reloads
    the page (with a cache-busting query string, so it can't just serve
    a browser-cached copy of the same stale HTML) shortly after this
    many minutes -- otherwise a browser tab left open on the page would
    keep showing the snapshot from whenever it was first loaded, forever,
    even though the server re-renders on schedule. A small buffer is
    added on top so the reload lands after the next render/upload has
    actually landed, not exactly when it starts.
    """
    os.makedirs(publish_dir, exist_ok=True)
    mirror_static_dir = os.path.join(base_dir, "static", "mirror")

    snapshot = _fetch_snapshot(api_app)
    generated_at = datetime.now().isoformat(timespec="seconds")

    # -- CSS, fonts inlined as base64 data URIs --------------------------
    with open(os.path.join(mirror_static_dir, "mirror.css"), "r", encoding="utf-8") as f:
        css = f.read()
    src_fonts = fonts_dir or os.path.join(mirror_static_dir, "assets", "fonts")
    css, fonts_embedded = _inline_fonts_as_data_uris(css, src_fonts)
    if fonts_embedded == 0:
        log.warning("No fonts embedded (looked in %s) -- exported page will "
                     "fall back to the system sans-serif font.", src_fonts)

    # -- mirror.js and the fetch-shim, inlined verbatim ------------------
    with open(os.path.join(mirror_static_dir, "mirror.js"), "r", encoding="utf-8") as f:
        mirror_js = f.read()

    data_snapshot_js = (
        f"window.MM_STATIC_GENERATED_AT = {json.dumps(generated_at)};\n"
        f"window.MM_STATIC_DATA = {json.dumps(snapshot, ensure_ascii=False)};\n"
    )

    script_parts = [
        "/* -- eingebackener Daten-Snapshot -- */",
        _escape_for_inline_script(data_snapshot_js),
        "/* -- fetch-shim: leitet mirror.js's fetch()-Aufrufe auf den Snapshot oben um -- */",
        _escape_for_inline_script(FETCH_SHIM_JS),
    ]
    if reload_interval_min and reload_interval_min > 0:
        reload_ms = int(reload_interval_min * 60 * 1000) + AUTO_RELOAD_BUFFER_MS
        script_parts.append(
            "/* -- Auto-Reload: laedt die Seite neu, sobald der naechste "
            "Render-Zyklus fertig sein sollte, damit ein dauerhaft "
            "geoeffneter Tab nicht fuer immer auf dem ersten Snapshot "
            "haengen bleibt. */\n"
            "(() => {\n"
            f"    setTimeout(() => {{ location.href = location.pathname + '?t=' + Date.now(); }}, {reload_ms});\n"
            "})();"
        )
    script_parts.append("/* -- mirror.js, unveraendert -- */")
    script_parts.append(_escape_for_inline_script(mirror_js))
    inline_script = "\n".join(script_parts)

    # -- index.html: Grid-Gerüst aus static/mirror/index.html übernehmen,
    #    aber CSS/JS komplett inline statt per <link>/<script src> --------
    with open(os.path.join(mirror_static_dir, "index.html"), "r", encoding="utf-8") as f:
        html = f.read()
    html = html.replace(
        '<link rel="stylesheet" href="/static/mirror.css?v=__ASSET_VERSION__">',
        f"<style>\n{css}\n</style>",
    )
    html = html.replace(
        "window.MM_API_PORT = __API_PORT__;",
        "window.MM_API_PORT = 0; // unused here -- der eingebackene fetch-shim fängt jeden Aufruf ab",
    )
    html = html.replace(
        '<script src="/static/mirror.js?v=__ASSET_VERSION__"></script>',
        f"<script>\n{inline_script}\n</script>",
    )
    html = html.replace(
        "<title>Magic Mirror 3000</title>",
        f"<title>Magic Mirror 3000</title>\n    <!-- statischer Snapshot erzeugt {generated_at} -->",
    )
    _atomic_write(os.path.join(publish_dir, "index.html"), html)

    log.info("Static mirror snapshot (single-file) written to %s (%s)", publish_dir, generated_at)
    return publish_dir


class StaticMirrorScheduler:
    """Background thread that re-renders the static mirror snapshot every
    N minutes. N (and the publish/fonts dirs) are read fresh from
    get_settings_fn() on every tick, so changes saved in the admin UI take
    effect without needing to restart the process. Same start()/stop()/
    is_running() shape as sftp_sync.SftpSyncService on purpose, so both
    can be wired into the admin UI the same way."""

    def __init__(self, api_app, base_dir, get_settings_fn):
        self._api_app = api_app
        self._base_dir = base_dir
        self._get_settings = get_settings_fn
        self._thread = None
        self._stop_event = threading.Event()
        self._control_lock = threading.Lock()
        self.last_error = None
        self.last_render_ts = None

    def is_running(self):
        return self._thread is not None and self._thread.is_alive()

    def start(self):
        with self._control_lock:
            if self.is_running():
                return
            self._stop_event.clear()
            self._thread = threading.Thread(target=self._loop, daemon=True)
            self._thread.start()
            log.info("Static mirror scheduler started.")

    def stop(self):
        with self._control_lock:
            if not self.is_running():
                return
            self._stop_event.set()
            self._thread.join(timeout=10)
            self._thread = None
            log.info("Static mirror scheduler stopped.")

    def render_now(self):
        settings = self._get_settings()
        publish_dir = settings.get("publish_dir") or os.path.join(self._base_dir, "publish")
        fonts_dir = settings.get("fonts_dir") or None
        interval_min = float(settings.get("interval_min") or DEFAULT_INTERVAL_MIN)
        try:
            render_static_mirror(self._api_app, self._base_dir, publish_dir, fonts_dir,
                                  reload_interval_min=interval_min)
            self.last_error = None
            self.last_render_ts = time.time()
            return True
        except Exception as e:
            self.last_error = str(e)
            log.error("Static mirror render failed: %s", e)
            return False

    def _loop(self):
        while not self._stop_event.is_set():
            settings = self._get_settings()
            interval_min = float(settings.get("interval_min") or DEFAULT_INTERVAL_MIN)
            interval_min = max(interval_min, MIN_INTERVAL_MIN)
            self.render_now()
            self._stop_event.wait(interval_min * 60)
